nuxt/image

docs/content/en/examples/random-provider.md, docs/content/en/nuxt-image.md
=> docs: fix code indentation

docs/content/en/setup.md
**bash** `.nuxt.config.js` → **js** `nuxt.config.js`
=> docs(setup): fix syntax highlighting

docs/content/en/options.md
=> docs(options): fix typo conig → config

docs/content/en/providers.md, playground/nuxt.config.ts, src/providers/fastly/index.ts, src/providers/fastly/runtime.ts, test/providers.test.ts
This adds a [fastly image optimization](https://docs.fastly.com/en/guides/image-optimization-api) provider.
- I tried to get the size operator matched up as much as I could, but they only have three options. 
- I added a fastly url, but because it's a demo url, the only available image to test on is [`/image.jpg`](https://www.fastly.io/image.jpg)
=> feat: add fastly provider

docs/content/en/options.md
Just some typos I found when reading the docs for the options 😊 hope this change is okay?
=> docs: resolve typos

docs/content/en/custom-provider.md, docs/content/en/nuxt-image.md, docs/content/en/nuxt-picture.md, docs/content/en/options.md, docs/content/en/providers.md
Hello 👋 
I noticed a few typos as I was reading through the documentation, so I thought I'd suggest some fixes. Please let me know if any of my proposed changes don't align with the original intention and I'll gladly edit them 🙂
=> docs: fix typos in content

docs/content/en/providers.md
adding back quotes to imgix to match styling of other image provider titles in docs
=> docs: add back quote to imgix

playground/layouts/default.vue, src/runtime/nuxt-image-mixins.ts, src/runtime/nuxt-image.ts, src/runtime/nuxt-picture.ts
Doing wrong with `nuxt-image` should not lead page crash. When the user uses an invalid provider or preset Image module throw an exception, We need to catch these exceptions to prevent page crash.  
Instead we can show the exception message inside `nuxt-image`.
=> feat(runtime): catch image exceptions and prevent page crash

playground/nuxt.config.ts, src/index.ts, src/runtime/image.ts, templates/plugin.js, types/module.d.ts, types/runtime.d.ts
As Josh described in #39 We sould eager load images below viewport by using proper value for `rootMargin`.   
This PR introduces a module option called `intersectOptions` to customize `IntersectionObserver`
=> feat: add module option to modify `IntersectionObserver` options

package.json, src/index.ts, src/providers/fastly/runtime.ts, src/providers/imgix/runtime.ts, src/providers/local/runtime.ts, src/runtime/image.ts, src/runtime/meta.ts, src/runtime/nuxt-image-mixins.ts, tsconfig.json, types/runtime.d.ts, yarn.lock
Previously we was depending on providers to resolve image meta (getting aspect ratio and also base64) this was adding complexity and sometimes extera requests. With this PR, using [nuxt-contrib/image-meta](https://github.com/nuxt-contrib/image-meta) (for Node.js) and `Image` + `Canvas` (for Browser), we can universally have ratio. (Future release of `image-meta` may eventually support Node.js if we can remove Buffer dependency)
=> feat: universal meta resolving

docs/content/en/providers.md, playground/nuxt.config.ts, src/index.ts, src/providers/local/index.ts, src/runtime/image.ts, src/runtime/nuxt-image-mixins.ts, templates/plugin.js, test/fixture/utils/componet.ts, test/unit/image.test.ts, test/unit/picture.test.ts, test/unit/plugin.test.ts, types/module.d.ts, types/runtime.d.ts
With this PR:
- Image utility has sizes operation
- Module listen to a random port for internal usage
- Image utility detects client-side rendering and fallback to the original image on static images
- Rename data property to `nuxtImageMap` in order to reduce conflict possibility with users data
- Use default sizes if the user does not provide sets
=> refactor image utility

src/providers/cloudinary/runtime.ts, test/unit/plugin.test.ts, test/unit/providers.test.ts
Add the following:
1. More types for resizing "fit"
2. Add default format and quality
3. Remove extension for Cloudinary images since they are not needed.
4. Fix unit tests.
=> fix(cloudinary): fit types, auto format & quality

src/runtime/meta.ts
=> fix: improve error readability

docs/content/en/custom-provider.md
=> docs: fix grammar mistake in custom-provider

src/runtime/image.ts, src/runtime/utils/index.ts
- Recursively apply default options
- Copy modifiers reference to ensure provider cannot have side-effects
- Preserve target format to apply as default after getting image object from provider
--- 
When you run `npx nuxt generate playground  --force-build`, only images in the original format are generated because the `format` field is removed from the `options` (src/runtime/image.ts#106) object.
This PR fixes it
*Before*:
```
✔ Generated static image playground/dist/_nuxt/image/71c8ed.jpg                                           @nuxt/image 10:25:44
✔ Generated static image playground/dist/_nuxt/image/361279.jpg                                           @nuxt/image 10:25:44
✔ Generated static image playground/dist/_nuxt/image/9fa6ff.jpg …
```
=> fix(image): use defu for options and fix default format

src/runtime/utils/observer.ts
Not sure if this is already in the process of being done, but a fallback is needed for the print listener on Safari <=13 (not sure on 14) as `MediaQueryList` still only supports `addListener` :)
=> fix(observer): add `mediaQueryList` listener fallback for safari/older browsers

.gitignore, docs/content/en/4.providers/vercel.md, playground/nuxt.config.ts, playground/pages/index.vue, src/module.ts, src/provider.ts, src/runtime/providers/vercel.ts, src/types/module.d.ts
Support vercel provider (https://vercel.com/docs/more/adding-your-framework#images)
Core changes:
- Provider auto detection based on env (default is `auto`)
- Provider `setup` option to generate `.vercel_build_output/config/images.json`
=> feat: vercel image provider

src/runtime/image.ts, src/runtime/utils/static-map.ts
* Worth also considering whether to use `fetch` (object syntax, but would require Nuxt 2.15+) vs `data` (?)
closes #234 
Likely also addresses https://github.com/nuxt/image/issues/167#issuecomment-826439905, https://github.com/nuxt/image/issues/215#issuecomment-826449532
=> fix: ensure static image map is available on first load

src/provider.ts, src/runtime/providers/vercel.ts
This fixes vercel auto-detection (note the issue was only with older deployments that didn't have system environment variables exposed to the build). 
In addition, if `vercel` provider is manually selected, in development `@nuxt/image` will provide warnings if un-configured widths are used (or if no width is set manually) to prevent issues in deployment. As `@nuxt/image` is transpiled, this will be tree-shaken out in build.
=> fix(vercel): fix vercel auto-detection and provide local vercel mode

src/runtime/providers/cloudinary.ts, test/providers.ts
* https://cloudinary.com/documentation/image_transformations#supported_image_formats
closes #254
=> fix(cloudinary): use `jpg` instead of `jpeg`

src/module.ts
Register components in `vue-loader` to resolve asset urls inside Vue templates.
=> fix: vue-loader support for PascalCase components

docs/content/en/3.api/2.$img.md
How to use the  [getSizes function](https://github.com/nuxt/image/blob/main/src/runtime/image.ts#L134-L192) and how to get a list of responsive image urls.
resolves #192
=> docs: document `$img.getSizes`

docs/content/en/3.providers.md, docs/content/en/4.providers/prismic.md, playground/nuxt.config.ts, playground/providers.ts, src/provider.ts, src/runtime/providers/imgix.ts, src/runtime/providers/prismic.ts, src/types/module.ts, test/providers.ts, test/unit/providers.test.ts
Add [Prismic](https://prismic) provider~ cc @pi0
closes #150
=> feat: add prismic provider

docs/content/en/4.providers/prismic.md
Following #269, there was a typo in the code snippet formatting from @danielroe (https://github.com/nuxt/image/pull/269#discussion_r633386151, https://github.com/nuxt/image/pull/269/commits/21aff062deac40d63cc755ac97aa1fc438636a13), literally made the commit at the exact same time @pi0 merged haha 🙏
Let me know if anything, cheers!
=> docs: fix typo in code snippets

docs/content/en/2.setup.md
Without this, references to `$img` on the context will throw an error
=> docs: add typescript setup notes

docs/pages/en/4.providers/ipx.md
Fixes a code block label typo. `mpm` -> `npm`
=> docs: fix typo

docs/pages/en/4.providers/netlify.md, playground/nuxt.config.ts, playground/providers.ts, src/provider.ts, src/runtime/providers/netlify.ts, test/providers.ts, test/unit/providers.test.ts
This adds support for the Netlify image transformation service.
Note that if you want to use this, you will need to enable [Netlify Large Media](https://docs.netlify.com/large-media/overview/) on Netlify.
More information: https://docs.netlify.com/large-media/transform-images/
=> feat: add support for netlify provider

docs/pages/en/4.providers/imagekit.md
Closes #271.
Added basic documentation for ImageKit, based on Imgix.
Tested this on a new Nuxt.js project and worked just fine.
=> docs: add imagekit documentation

src/runtime/image.ts
* context: https://github.com/nuxt/image/pull/284
I'm not sure why `beforeNuxtRender` isn't properly setting the page data but this does fix the issue
closes #297
=> fix: ensure payload includes up-to-date _img

docs/pages/en/4.providers/sanity.md, playground/nuxt.config.ts, playground/providers.ts, src/runtime/providers/sanity.ts, test/providers.ts, test/unit/providers.test.ts
* intelligent hotspot & cropping support
* same fit, format behaviour as default modifiers
* convenience modifiers for greater readability
* enables format=auto by default
* adds sanity test suite
* fixes background
* supports boolean values (dl & invert)
=> feat(sanity): sanity provider enhancements

docs/pages/en/2.components/1.nuxt-img.md
Since developers may be used to managing their images in the `assets` folder, this provides clarity on where to store images and why for developers who may not be as familiar with the build system.
=> docs: clarify src origin

docs/pages/en/1.getting-started/2.providers.md, docs/pages/en/2.components/1.nuxt-img.md, docs/pages/en/4.providers/ipx.md
I think default behavior is missing for IPX. 
Adding this will add more clarity. But for the alternative serverMiddleware the default behavior is a bit mistyc. Is it recommended to put it inside static folder ?
Because if you do that you have use `/static/myimg` when the default behavior for other is not set the `static`
Don't know what you think about it.
=> docs: document where to put static images

src/generate.ts, src/runtime/image.ts, src/types/image.ts, src/utils.ts
This fixes an issue with the static provider on remote domains including query params in the `nuxt generate` filename outputs.
Say I have `domains: ['https://images.prismic.io']` in my nuxt config and passing an src like `https://images.prismic.io/blog-system76/30e9de39-20a6-4caf-8728-0ec917942a0f_tumblr_4fef1ab602684355ef9596a0b9fdb122_810bfad7_1280.png?auto=compress,format&rect=56,0,700,700&w=800&h=800`, the generated nuxt image file path would end up looking like `dist/_nuxt/image/181d93.png%3Fauto=compress,format&rect=56,0,700,700&w=800&h=800`.
This PR changes it to output `dist/_nuxt/image/181d93.png` by stripping anything after `%3F` which is the url encoded `?`
=> fix(static): url encoded name included in generated ext

docs/content/en/4.providers/ipx.md
Fixes #351.
Add instructions on how to use IPX modifiers and
also instructions on how to use animated images.
=> docs(ipx): instructions for modifiers

docs/content/en/4.providers/contentful.md, playground/nuxt.config.ts, playground/providers.ts, src/provider.ts, src/runtime/providers/contentful.ts, src/types/module.ts, test/providers.ts, test/unit/providers.test.ts
Resolve #330
It uses Contentful's [Images API](https://www.contentful.com/developers/docs/references/images-api/)  to transform images.
=> feat: add contentful provider

docs/content/en/4.providers/ipx.md
Change "an usecase" to " a use case"
=> docs(ipx): fix typo

docs/content/en/2.components/1.nuxt-img.md, src/runtime/components/image.mixin.ts, src/runtime/components/nuxt-img.vue, src/runtime/components/nuxt-picture.vue
adds a `preload` property to inject a link-tag vie nuxt's `head()` function. works with `nuxt-img` as well as `nuxt-picture` and also with responsive images.
fixes #105
=> feat: add preload functionality

src/runtime/providers/vercel.ts
Default `.sort` method converts elements into strings and then sorts them in ascending order.
```
const validWidths = Object.values(sizes || {}).sort()
> [100, 1200, 150]
```
```
const validWidths = Object.values(sizes || {}).sort((a, b) => a - b)
> [100, 150, 1200]
```
=> fix(vercel): sort valid widths before picking largest

docs/content/en/2.components/1.nuxt-img.md
Lazy loading is mentioned as a feature for <nuxt-img> so provide
more details and an example.
=> docs: mention lazy loading for <nuxt-img>

src/types/module.ts
=> feat(cloudinary): add types for options and modifiers

docs/content/en/4.providers/storyblok.md, playground/nuxt.config.ts, src/runtime/providers/storyblok.ts
Updates the `storyblok` provider to use their new [Image Service API](https://www.storyblok.com/docs/image-service#migrating-from-the-previous-version-of-the-service).
Linked to #474.
=> feat(storyblok): update to the new service

src/runtime/components/nuxt-img.vue, src/runtime/components/nuxt-picture.vue
Fixes #527 where not preloading images causes the app to throw an error.
=> fix(nuxt-img, nuxt-picture): return empty object from `head` when preload is disabled

docs/content/1.getting-started/1.installation.md
As of Nuxt 3, `buildModules` property is deprecated. Use `modules` instead.
=> docs: advice `modules` instead of `buildModules`

docs/content/1.getting-started/1.installation.md
v1.image.nuxtjs.org does not contain a /get-started/installation route. The directions for installation are at that route.
Also, the actual route is "get-started" vs "getting-started". Not sure if someone wants to fix that.
=> docs: fix broken link

src/runtime/components/nuxt-img.ts
=> fix(nuxt-img): access `prerender.env` only in server side

docs/content/5.providers/cloudflare.md
The example in the documentation for the Cloudflare provider is missing the parent `cloudflare` object. The current example doesn't work on the latest version.
=> docs: fix cloudflare usage example

src/ipx.ts
fix #704 
Pass ipx maxAge option from `nuxt.config.ts`.
```ts
// nuxt.config.ts
export default defineNuxtConfig({
// ...
image: {
ipx: {
maxAge: 2592000,
},
},
// ...
})
```
=> fix(ipx): pass `maxAge` to ipx options

src/module.ts, src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts, src/runtime/providers/ipx.ts, src/runtime/utils/prerender.ts
Fixes various issues related to static image prerendering.
close #701 (thanks @posixpascal) close #674 (thanks @jimhlad)
should generally resolve issues in #671 and #689
Changes:
- Use a new internal util `prerenderStaticImages`
- Properly split with `, ` (instead of `,`)
- Encode each path before pushing to header (**requires Nitro 2 / Nuxt 3.1**)
- Avoid adding empty headers
- Support prerendering for `nuxt-picture` as well
- Use `&` as modifier splitter in ipx provider links in order to support **windows** paths.
=> fix!: improve prerendering support

src/module.ts
fixes https://github.com/nuxt/image/issues/659
=> fix: normalize `options.domains` with host and port

docs/content/5.providers/cloudinary.md, src/runtime/providers/cloudinary.ts
- update mapping key for cloudinary `density` from `dpi` to `dn`. https://cloudinary.com/documentation/transformation_reference#dn_density
- add support for aspect ratio
=> fix(cloudinary): update mapping key for `density`

playground/providers.ts, src/runtime/providers/unsplash.ts
Edits done: Edited the provider for Unsplash, added a new case to the playground for Unsplash
Hi everyone, I found out that when using URLs which already contains query parameters, the provider will wrongly attach a '?'  instead of using a & before the applied operations and Unsplash would ignore the first passed operation. 
In these cases, placing a & would be the correct option.
I think another workaround would be to always place a '&' after '?' Like this: `?&`  but I don't think is elegant.
Here's an example of one generate url wrong: 
https://images.unsplash.com/photo-1532236204992-f5e85c024202?crop=entropy&cs=tinysrgb&fm=jpg&ixid=MnwxOTgwMDZ8MHwxfHNlYXJjaHwyOHx8dG9reW98ZW58MHx8fHwxNjczNzk3MDIz&ixlib=rb-4.0.3&q=80?w=300&q=80
The wrong part: ` &q=80?w=300&q=80`
Here's how it should …
=> fix(unsplash): merge query params with src

docs/content/4.api/2.$img.md
Usage chapter example updated. There was a typo in returned object.
=> docs: fix typo in api docs

src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts
This commit adds data attributes to usages of nuxt/image and nuxt/picture. This will allow us to compare performance results (in aggregate) for apps that use the components against apps that use normal `<img>` or `<picture>` tags. Currently, it isn't possible because there isn't a good way to distinguish the two in HTTP Archive.
Doing such a perf comparison allows us to:
- ensure that these components actually improve performance
- catch and fix performance regressions quickly
=> feat: add data-nuxt-img and data-nuxt-pic attrs

src/ipx.ts, src/runtime/ipx.ts
resolves https://github.com/nuxt/image/issues/749
resolves https://github.com/nuxt/image/issues/758
This removes hardcoded relative paths for the public dir. In so doing it fixes a couple of bugs with netlify, but also for any other preset which didn't output to `../public` (next to a server directory).
=> fix(ipx): use actual relative ipx dir

src/module.ts, src/runtime/plugin.ts, src/runtime/providers/ipx.ts, src/types/image.ts
resolves https://github.com/nuxt/image/issues/665
https://github.com/nuxt/image/discussions/548
This adds a new property `nuxt.baseURL` to global image options. Providers like IPX can take this into account when rendering their image URLs.
Some linting also took place in the types file - apologies, I couldn't resist, but I separated out the commit.
=> fix(ipx): support runtime nuxt `baseURL` 

src/ipx.ts
resolves https://github.com/nuxt/image/issues/780
The Nitro prerenderer does not share the same runtimeConfig instance so we can set it on `_config`.
Opening the PR as hotfix but we may also want to change behaviour in nitro or provide a hook to allow us to configure the prerenderer more specifically (even just another call of `nitro:config` would be ideal).
=> fix(ipx): set prerenderer config as well

src/ipx.ts
https://github.com/nuxt/image/issues/780#issuecomment-1489048172
Ugh. Apologies for the iteration on this one. I think we'll need to use an absolute path for the prerenderer, and relative for the built version.
=> fix: use absolute path for prerenderer

src/runtime/components/nuxt-picture.ts
The resulting value of format.value will always be "svg" if a custom format is provided
=> fix: correctly apply provided format to `<NuxtPicture>`

package.json
This PR should resolve https://github.com/nuxt/image/issues/379
I'm open for any kind of feedback or improvement.
=> fix(pkg): use esm build as `main` field

src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts, test/e2e/no-ssr.test.ts, test/e2e/ssr.test.ts
resolves https://github.com/nuxt/image/issues/682
resolves https://github.com/nuxt/image/issues/412
This PR emits load/error events on initial hydration for better DX if the load/error event has already occurred before hydration.
=> fix: emit synthetic load/error events on initial hydration

package.json, pnpm-lock.yaml
Image module support for Nuxt 3 has been started since [Jul 8, 2022](https://github.com/nuxt/image/discussions/548). After months of progress and continuous feedback, this is the first (semi-stable) version of the Image module ready for Nuxt 3 🚀 
Over the RC releases, we plan to mainly stabilize the module and add some enhancements:
- Addressing most demanded feature requests and bug fixes
- Support multi-sources and server-side caching using Nuxt 3's built-in [Storage Layer](https://nuxt.com/docs/guide/directory-structure/server#server-storage) for default image optimizer ([unjs/ipx](https://github.com/unjs/ipx))
- Better support for screen densities
- Better support for static output targets
- Improve for easier integration with Nuxt 3 Core
- Initial rewrite for nuxt 3 support …
=> v1.0.0-rc.0

src/runtime/providers/storyblok.ts
Given the nature of headless CMS we sometimes don't know what image type will be passed into `nuxt-img`. This prevents any resizing, formatting and filtering on vector images. Today if any of these are applied storyblok either responds with a `40X` error or the image appears distorted.
=> fix(storyblok): don't apply resize/format/filter on vector

src/runtime/components/nuxt-img.ts, src/runtime/image.ts, src/runtime/utils/index.ts, src/types/image.ts, test/unit/image.test.ts, test/unit/picture.test.ts
=> fix: address miscellaneous bugs with new 'densities' prop

docs/content/5.configuration.md, src/module.ts, src/runtime/components/_base.ts, src/types/image.ts, test/unit/image.test.ts, test/unit/picture.test.ts
Hi there 👋 
This PR allows setting the quality of the generated images in the module configuration.
Thank you very much for the amazing work 🚀
=> feat: allow setting global `quality` defaults in config

src/runtime/image.ts, src/runtime/utils/index.ts
resolves https://github.com/nuxt/image/issues/912
This PR warns in dev mode if user is setting a density > 2x, linking to https://observablehq.com/@eeeps/visual-acuity-and-device-pixel-ratio.
It doesn't hard-disable this although this might be something we consider in future.
This also refactors the density parsing expression slightly to use a Set for deduplicating.
=> fix: warn in dev mode if density is provided above 2x

docs/content/2.usage/1.nuxt-img.md, src/runtime/image.ts, src/runtime/utils/index.ts, test/unit/image.test.ts, test/unit/picture.test.ts
resolves https://github.com/nuxt/image/issues/645
This aims to enable responsive sizing by default. It has two breaking changes:
1. sizes without an explicit screen width (e.g. `sizes="100vw"`) are interpreted as a _responsive_ minimum size, e.g. `1px:100vw`.
2. Sizes are output from that screen-size _up_ rather than that screen-size _down_, so `sizes="md:100px lg:200px"` means that the image is displayed at `100px` by default. And at `lg` and above, at `200px`. (Previously, this meant that it was displayed at 100px only up to `md`, and then displayed at `200px` for all sizes above that.)
As these are both significant changes from previous behaviour, special care is requested in evaluating the API and DX.
=> feat!: switch `sizes` default to responsive-first

package.json
> 1.0.0-rc.2 is the next release candidate
>
> **Timetable**: 13 September
- We now support densities - and warn if you use a density above 2x (https://github.com/nuxt/image/pull/769).
- We now support multiple formats in `<NuxtPicture>` and setting global default values.
- 🚨 **This is a behaviour change**. We now default to responsive-first image sizes, and output sizes/srcset even when only a single size is provided. See https://github.com/nuxt/image/pull/977 for full details.
- We now support purely-generate-time static images for environments like cloudflare (https://github.com/nuxt/image/pull/878).
There's lots more - do check out the full details below.
Our next RC will be coming soon with all-new IPX v2, as well as some work on better defaults (e.g. automatic format detection where …
=> v1.0.0-rc.2

docs/content/3.providers/unsplash.md
Supported parameters were incorrectly being displayed as a paragraph without line breaks. Rather than just adding line breaks, change the paragraph to a bulleted list to improve readability.
=> docs: display supported unsplash parameters as a list

docs/content/2.usage/1.nuxt-img.md, src/runtime/components/_base.ts, src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts, test/unit/image.test.ts
=> feat: add `nonce` support

src/runtime/providers/cloudinary.ts, test/unit/providers.test.ts
=> fix(cloudinary): handle blur modifier correctly

playground/providers.ts, src/runtime/providers/cloudimage.ts, test/e2e/__snapshots__/no-ssr.test.ts.snap, test/e2e/__snapshots__/ssr.test.ts.snap
**Problem**
* **Cloudimage**: Images starting with `HTTP` should not be prefixed with `Base Url`
**issues**
* https://github.com/nuxt/image/issues/1026
**Solution**
* Add condition if src `startwith http` return src with generate query parameters
**Before:**
* `https://token.cloudimg.io/__path__/https://2412819702-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FlIgyYELwJG6odLEyCM6i%2Fuploads%2FAHcbuKRYbIlBWO4cJ88b%2Fimage.png?alt=media&token=62ff753d-83eb-4e3f-932c-96eb72d455f1?height=100&width=100&q=65&func=crop`
**After:**
* `https://2412819702-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FlIgyYELwJG6odLEyCM6i%2Fuploads%2FAHcbuKRYbIlBWO4cJ88b%2Fimage.png?alt=media&token=62ff753d-83eb-4e3f-932c-96eb72d455f1?height=100&width=100&q=65&func=crop` …
=> fix(cloudimage): skip cdn when `src` path is provided with protocol

docs/pages/index.vue
Just a small update to add the native browser tooltip for the providers in the home page. This way people who don't recognize a particular logo can just hover over the icons and see the provider's name.
=> docs: add title to provider links

playground/nuxt.config.ts, src/ipx.ts, src/module.ts, src/types/module.ts
Rework of #976
Pass all IPX provider options correctly.
Slight breaking change before 1.0.0: `sharp` has been moved under `ipx.sharpOptions` to allow future changes for IPX decoupling from image module top-level options.
=> fix(ipx)!: pass all options

docs/content/3.providers/aws-amplify.md, docs/content/3.providers/vercel.md
The documentation states that the image provider will fallback to the >nearest< image width when a image width was not defined in the screens option. This is not the actual behavior. Actually, the next bigger screen width is return. I've tried to reflect this with this change.
=> docs: explain fall back to larger size on amplify + vercel

docs/content/3.providers/netlify.md
**Just a minor thing!**
Netlify Large Media is deprecated. I added a small inline warning at the top of the documentation with some remarks from the official documentation. I linked to the official forum for a more in depth explanation.
I was wondering if this should also be mentioned in the title?
You could also argue that 'Netlify' should be hidden from the 'providers' navigation?
=> docs: added deprecated message Netlify Large Media

docs/content/3.providers/hygraph.md, docs/pages/index.vue, docs/public/providers/hygraph.svg, playground/nuxt.config.ts, playground/providers.ts, src/provider.ts, src/runtime/providers/hygraph.ts, test/e2e/__snapshots__/no-ssr.test.ts.snap, test/e2e/__snapshots__/ssr.test.ts.snap, test/providers.ts
To my surprise, there was no Nuxt/Image provider for Hygraph yet!
=> feat: add `hygraph` provider

docs/content/1.get-started/1.installation.md
There was no installation command for Bun. In Nuxt documentation there are commands for bun so I think it would be good for consistency to add it there too
=> docs: add bun installation command

src/runtime/components/nuxt-img.vue
Adds support to preload responsive images on V0
resolves #612 
Logic copied from `main` version:
https://github.com/nuxt/image/blob/36285464fc10b4d6e7ad8bf166d89e6d09ff88df/src/runtime/components/nuxt-img.ts#L82
=> Add support to preload responsive images on V0

docs/content/3.providers/imagekit.md, src/runtime/providers/imagekit.ts
old overlay syntax is [obsolete](https://docs.imagekit.io/features/image-transformations/overlay) and "layers" are now used to generate overlay transformations. This update removes old syntax and replaces it with the new one.
=> feat(imagekit): replace obsolete overlay syntax with layers

src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts, src/runtime/utils/performance.ts
Feature detection was added in #747 to allow performance analysis for nuxt/image uses in aggregate. Since that time, Javascript-based feature markers have been standardized in the W3C group around the User Timing API:
https://www.w3.org/TR/user-timing/#dfn-mark_feature_usage
This commit updates the feature tracking to use the new standard, which is designed to be performance-neutral. The previous mechanism (the data- attributes) will be removed in a future PR, once we can confirm it works as expected end-to-end.
=> update feature detection markers to match new standard

package.json, pnpm-lock.yaml
Downgrade ipx to 2.1.0 to avoid issues with `sharp` (#1257, #1210, #1237, #1253, #1262, #1264, #1228, #1227) until https://github.com/unjs/ipx/issues/215 is resolved. [@pi0 comment on Discord](https://discord.com/channels/473401852243869706/847861019421179994/1211757315070627910).
=> fix(ipx): temporarily downgrade ipx/sharp

docs/content/1.get-started/1.installation.md, docs/pages/index.vue
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
=> docs: use new `nuxi module add` command in installation

src/runtime/components/nuxt-img.ts, test/unit/image.test.ts
As described in this Vue core issue (https://github.com/vuejs/core/issues/10764), using the `src` attribute before `loading` results in the lazy-loading being inconsistent across loads. This PR moves the `src` tag to the last position in the element.
I tested the behavior before and after the change in the playground to confirm it is working correctly. If you want I can also commit the playground page for reference.
Feel free to correct me on anything I might have done wrong, be it in the code or while making this PR. I'm not very experienced with the process of contributing to public repos yet!
=> fix: move src attribute to end of <img> tag to fix lazy loading (#1317)

docs/content/1.get-started/1.installation.md
Just a quick fix. There are some typos in the sentence.
=> docs: fix typo in get-started/installation

src/runtime/providers/cloudinary.ts
This fixes the mapping for the default "cover" fit mode between nuxt-image and cloudinary.
It was previously mapped to cloudinary's "fit" mode where it should be mapped to their "lfill" mode.
Related to issue #1354
=> fix(cloudinary): map `cover` to cloudinary's `lfill` mode

docs/content/2.usage/1.nuxt-img.md
I noticed some variation in notation in the `<NuxtImg>` documentation.
- https://image.nuxt.com/usage/nuxt-img
Therefore, I have standardized it from `<nuxt-img>` to `<NuxtImg>`.
=> docs: fix inconsistent spelling

src/runtime/providers/weserv.ts
resolves https://github.com/nuxt/image/issues/1408
Rotation operator should be mapped to `ro` instead of `rot`, as per [docs](https://wsrv.nl/docs/orientation.html#rotation).
=> fix(weserv): map rotate operation to `ro`

src/runtime/components/NuxtImg.vue
resolves https://github.com/nuxt/image/issues/1443
Renames `_attrs` to `imgAttrs` in `<NuxtImg>` component.
=> fix: prevent hydration mismatch in `<NuxtImg>`

src/runtime/components/_base.ts
It feels like this might be a vue bug with prop type inference, but otherwise strange errors were occurring, e.g.:
```vue
<template>
<NuxtImg
v-if="uwuCookie"
sizes="343px md:455px"
width="455"
height="256"
class="mx-auto lg:my-16"
src="/uwu.png"
alt="Nuxt Logo in uwu style"
/>
</template>
```
```
pages/index.vue:86:9 - error TS2322: Type 'string' is not assignable to type 'undefined'.
86         sizes="343px md:455px"
~~~~~
```
> https://github.com/nuxt/nuxt.com/actions/runs/10596463874/job/29364485513?pr=1650
=> fix: use `required: false` rather than `default: undefined` for props

src/module.ts, src/runtime/composables.ts, src/types/image.ts
resolves #1247
This change passes the runtime config to the `getImage` function of an image provider. It allows built-in or custom providers to support options that are configured at runtime rather than build time.
=> feat: provide runtimeConfig to getImage function (#1247)

src/runtime/index.ts
resolves https://github.com/nuxt/image/issues/1460
Likely related to https://github.com/nuxt/module-builder/issues/308.
=> fix: suffix export of runtime utils with `/index`

docs/content/3.providers/vercel.md, src/provider.ts, src/runtime/providers/vercel.ts
Fix #1490
Fix #1455
Fix #1107
Closes https://github.com/nuxt/image/pull/1181
- Added the missing `formats` in nitro Vercel config & updated docs to avoid missing the fact that every custom sizes need to be specified using Vercel image optimizer.
- Without `formats`, Vercel does not resize images.
=> fix(vercel): added missing `formats` config & improved documentation

docs/content/3.providers/cloudflare.md
Resolves https://github.com/nuxt/image/issues/1546 and https://github.com/nuxt/image/issues/805.
The documentation for Cloudflare is missing an important step, which is to enable image transformations for the deployment URL at Cloudflare dashboard. Otherwise, the module does not work and it causes a lot of confusion for initial setup. This PR aims to clarify this with a warning callout.
=> docs: improve cloudflare provider page

src/runtime/components/NuxtImg.vue, test/unit/image.test.ts
resolves #1639 
I need to deal with the ERROR event when the picture is loaded, but if I use the Placehoder attribute at the same time, the ERROR event will not be thrown out
```javascript
onMounted(() => {
if (placeholder.value) {
const img = new Image()
if (mainSrc.value) {
img.src = mainSrc.value
}
if (props.sizes) {
img.sizes = sizes.value.sizes || ''
img.srcset = sizes.value.srcset
}
// !!! Here, if the IMG loading error, there is no ERROR incident !!!
img.onload = (event) => {
placeholderLoaded.value = true
emit('load', event)
}
// add this to fix
img.onerror = (event) => {
emit('error', event)
}
markFeatureUsage('nuxt-image')
return
}
// ...other
}
```
=> fix: emit error events from `<NuxtImg>` placeholder

src/runtime/components/NuxtPicture.vue
The `imgAttrs` property in `NuxtPicture` was not responsive as of yet. This commit changes that.
=> fix(NuxtPicture): make `img-attrs` and `attrs` responsive

docs/content/2.usage/1.nuxt-img.md
Just fixed a typo that caused confusion, as the code did not work as described.
No other typos were found to batch-fix.
=> docs: fix confusing typo in 1.nuxt-img.md

src/runtime/providers/cloudflare.ts
Should resolves #1080
Using Cloudflare means setting the baseURL as a domain.
But if no modifiers/operations are set, it will join the urls, making it fail when the source is an absolute url.
=> fix(cloudflare): don't add baseURL if no operations

src/runtime/providers/ipx.ts, src/runtime/providers/ipxStatic.ts
when using ipx in a static deployment, double slashes can lead to 404s on some providers. (this occurs when transforming images on external domains). we can solve by stripping them.
context: https://github.com/danielroe/roe.dev/blob/7704f70db1c756f28f557bd13875a29b11419ef7
=> fix(ipxStatic): strip repeated slashes from image path

src/ipx.ts, src/module.ts
With upcoming release of nuxt image including ipx v3, it's important to let users know the architecture they have built for.
This adds a log after the build is complete.
questions:
1. is it that important? we could move it earlier in the build pipeline rather than making sure it's the last thing users see
2. do we need to do more than add this log? the main thing is that it's there for is to help users debugging issues they might face
=> feat(ipx): log the architecture of the build

docs/content/4.advanced/1.custom-provider.md
updated github link in documentation to use the correct `main` branch instead of `dev` for the providers directory.
=> docs: fix link to runtime/providers (dev -> main)

docs/content/1.get-started/2.configuration.md, docs/content/2.usage/3.use-image.md, src/module.ts, test/unit/image.test.ts, test/unit/providers.test.ts
This aligns the default list of screen sizes with https://tailwindcss.com/docs/responsive-design.
=> feat!: remove `xs` and `xxl` screen sizes
