nuxt/image

docs/content/en/nuxt-picture.md
=> docs(nuxt-picture): fix typo foramt → format

docs/content/en/custom-provider.md, docs/content/en/examples/random-provider.md, docs/content/en/nuxt-image.md, docs/content/en/nuxt-picture.md, docs/content/en/setup.md, docs/content/en/usage.md
| Page | Position |
| --- | --- |
| Introduction | 1 |
| Setup | **1 → 2** |
| Usage | **2 → 3** |
| Options | 4 |
| Providers | 5 |
| Create Custom Provider | **5 → 6** |
| Image Component | **4 → 7** |
| Picture Component | **5 → 8** |
| Random Provider | **5 → 9** |
=> docs: fix prev/next navigation

docs/content/en/nuxt-image.md
=> docs: typo

docs/content/en/custom-provider.md, docs/content/en/how-it-works.md, docs/content/en/nuxt-image.md, docs/content/en/providers.md, docs/content/en/usage.md
=> docs: improve docs

docs/content/en/usage.md
=> docs: fix typo

docs/content/en/nuxt-img.md, docs/content/en/nuxt-picture.md, docs/content/en/providers.md, docs/content/en/providers/cloudinary.md, docs/content/en/providers/imgix.md, playground/pages/index.vue, playground/pages/picture.vue, playground/pages/responsive.vue, src/providers/cloudinary/runtime.ts
1. Fix examples of Cloudinary on playground.
2. Add documentation for Cloudinary providers.
3. Add additional mapping for operations.
4. Capitalize name of providers in docs, and fix minor typos.
5. Probably that's it :)
=> Cloudinary documentation, examples, extra operations and some minor fixes

docs/content/en/options.md, docs/content/en/providers/twicpics.md, playground/nuxt.config.ts, playground/pages/index.vue, playground/pages/picture.vue, playground/pages/responsive.vue, src/providers/twicpics/runtime.ts
* Fixes TwicPics runtime
* Updates TwicPics subdomain
* TwicPics playground examples
=> docs(twic-pics): provider fixes & examples

playground/nuxt.config.ts, playground/pages/index.vue, src/providers/imagekit/index.ts, src/providers/imagekit/runtime.ts, test/unit/providers.test.ts
- Added Imagekit Provider according to [docs](https://docs.imagekit.io/features/image-transformations/resize-crop-and-other-transformations).
- Added Test for Imagekit provider.
- Added an Example of imagekit in playround.
=> feat: imagekit provider implementation and tests

docs/content/en/custom-provider.md
Fixed the typo in the first line. Changed 'my' to 'may'.
=> chore(readme): fix typo

docs/content/en/nuxt-img.md
"I this case..." amended to "In this case..."
=> Fixed typo

docs/content/en/3.api/2.$img.md, docs/content/en/4.providers/ipx.md
I got stuck on these as I was going and resorted to digging through the code. 
Understand that this doc is not fully complete, hopefully, they can be a bridge to better docs in the future.
=> docs: document `$img` and ipx for static target

src/runtime/components/nuxt-img.vue
=> fix: generate static images even if lazy loaded

src/provider.ts
https://vercel.com/docs/environment-variables#system-environment-variables
=> fix: vercel provider improvements

docs/content/en/3.api/1.options.md
=> docs: document `dir` option

docs/nuxt.config.js
Add missing `head` property, fix broken meta tags
=> docs: fix meta tags

docs/pages/en/2.components/1.nuxt-img.md
Came across a lazy lading question/answer and added the response to the docs
=> docs: add clarifying language for lazy load support

src/runtime/providers/glide.ts
Use with base to prevent adding duplicate base url
=> fix(glide): prevent adding duplicate base url

package.json, src/ipx.ts, yarn.lock
Continue of #380 since cannot push changes to PR. Closes #379.
=> fix: move `ipx` to optional dependencies

docs/content/en/1.getting-started/0.index.md, docs/content/en/2.components/0.index.md, docs/content/en/3.api/0.index.md, docs/content/en/4.providers/0.index.md, docs/content/en/5.advanced/0.index.md, docs/content/index.md, docs/docus.config.ts, docs/nuxt.config.js, docs/package.json, docs/yarn.lock
Hey 😄, here is a PR fixing the Docus version to 1.1.x.
Please note the Docus API can expect a lot of changes in upcoming weeks/months, so I'll submit this kind of PRs more than once.
If you encounter any problem with that PR, please let me know!
Fixes:
https://github.com/nuxt/image/issues/409
https://github.com/nuxt/image/issues/407
=> chore(docs): update Docus (1.1.x)

docs/content/en/1.getting-started/1.installation.md
=> docs: add nuxt3 incompatibility warning

docs/content/en/3.api/1.options.md
=> docs: add example for default modifiers

docs/content/en/4.providers/cloudimage.md, playground/nuxt.config.ts, playground/providers.ts, src/provider.ts, src/runtime/providers/cloudimage.ts, src/types/module.ts, test/providers.ts, test/unit/providers.test.ts
=> feat: cloudimage provider

docs/content/en/4.providers/twicpics.md, playground/providers.ts, src/runtime/providers/twicpics.ts
TwicPics provider: 
- fixes `fit=contain` feature
- fixes `fit=inside` feature
- fixes `fit=outside` feature
- additional documentation and playground samples
=> feat(twicpics): fix modifiers and improve documentation

docs/content/en/4.providers/layer0.md, playground/nuxt.config.ts, playground/pages/provider/_provider.vue, playground/providers.ts, src/provider.ts, src/runtime/providers/layer0.ts, src/types/module.ts
resolves https://github.com/nuxt/image/issues/498
=> feat: layer0 provider

docs/content/2.components/1.nuxt-img.md
Different folder structure (static or public) based on Nuxt versions
=> docs: update `static/` dir to `public/`

src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts
This should implement the Nuxt Image "load" listener for both nuxt image components. It should also solve issue #682
=> feat: support `load` event for `nuxt-img` and `nuxt-picture`

src/runtime/providers/cloudinary.ts, src/types/module.ts
- remove dangle comma (fix failed ci)
- fix function name convention
- add autocomplete for `aspectRatio` modifier
=> style(cloudinary): remove dangle comma

src/runtime/providers/sanity.ts
Added `dpr` as key to be able to control the pixel density of the image
=> fix(sanity): add `dpr` modifier

src/module.ts
=> fix: run setup and add `none` to providers list

src/runtime/components/_base.ts
As per https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes
=> fix: autocomplete `<NuxtImg>` loading attribute

docs/content/3.providers/cloudinary.md
In this PR, I have added a note to the Cloudinary Provider about more advanced usage that can be delivered by using Nuxt Cloudinary.
=> #1117 Note about Cloudinary Module in Cloudinary provider

src/runtime/components/nuxt-img.ts, src/runtime/components/nuxt-picture.ts, src/runtime/image.ts, src/runtime/utils/meta.ts, src/runtime/utils/prerender.ts
This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
=> fix: opt in to `import.meta.*` properties

docs/content/3.providers/hygraph.md, playground/nuxt.config.ts, playground/providers.ts, src/runtime/providers/hygraph.ts, test/e2e/__snapshots__/no-ssr.test.ts.snap, test/e2e/__snapshots__/ssr.test.ts.snap, test/providers.ts
Backward compatible :)
resolves https://github.com/nuxt/image/issues/1295
=> Chore: updated image module for new Hygraph asset system.

docs/pages/index.vue
capitalize title like other titles for consistency.
=> docs: capitalize title

docs/content/3.providers/strapi.md
Refer available links through Strapi documentation
=> docs(strapi): recent links Upload configuration

package.json, pnpm-lock.yaml
This drops support for usage within CJS - which has never been needed by Nuxt v3.
=> build: update to latest `nuxt/module-builder`

.nuxtrc, vitest.config.mts
=> chore: remove unneeded `.nuxtrc` config

.github/workflows/changelogensets.yml, .github/workflows/ci.yml, .github/workflows/release-nightly.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml
This adds automated publishing of release PRs as well as pkg.pr.new integration.
=> ci: add release workflow and add pkg.pr.new

.npmrc
=> chore: disable `shamefully-hoist`

package.json, pnpm-lock.yaml
we're going to pair this PR with some enhancements (if needed) to make sure nitro traces the correct binaries for sharp when deploying
=> feat(deps): upgrade to ipx v3

docs/nuxt.config.ts, docs/package.json, pnpm-lock.yaml
Fix meta title from `{{ page title }} - docs` to `{{ page title }} - Nuxt Image` based on [site.name](https://github.com/nuxt/image/blob/main/docs/nuxt.config.ts#L8-L10)
=> docs(deps): upgrade docus to fix meta template title

docs/package.json, pnpm-lock.yaml
Currently "Copy page" button is broken because website is 100% pre-rendered (no server running). With the new version of Docus all raw markdown routes are also pre-rendered if the corresponding page is prerendered.
=> docs(deps): upgrade docus to fix raw markdown prerendering

docs/content/2.usage/1.nuxt-img.md, docs/content/2.usage/2.nuxt-picture.md
=> docs: fix components source file link

docs/.npmrc, docs/app/app.config.ts, docs/app/assets/css/main.css, docs/package.json, knip.json, pnpm-lock.yaml
Upgrade to Docus v5 using Nuxt UI v4 under the hood. `NUXT_UI_PRO_LICENSE` can safely be removed from env variables.
=> docs(deps): upgrade to docus v5
